#
# Module manifest for module 'PemCore'
#
# Generated by: Shawn Leonard
#
# Generated on: 1/15/2020
#

@{
	#RootModule = 'PemCore.dll'
	ModuleVersion        = '1.0.0.0'
	GUID                 = 'e5662a81-b6ce-41cf-977f-fff057c2da84'
	Author               = 'Shawn Leonard (sleonard@microsoft.com)'
	CompanyName          = 'Microsoft'
	Description          = 'This module is used to automate SSH'
	CompatiblePSEditions = 'Core', 'Desktop'
	PowerShellVersion    = "5.1"
	ClrVersion           = "4.0"
	FormatsToProcess     = 'PemCore.ps1xml' 
	RequiredAssemblies   = @('PemCore.dll', 'BouncyCastle.Crypto.dll', 'System.Runtime.CompilerServices.Unsafe.dll')
	NestedModules        = @('.\PemCore.dll')
  
	# Modules that must be imported into the global environment prior to importing this module  
	RequiredModules      = @()
	FunctionsToExport    = '*'
	CmdletsToExport      = '*'
	VariablesToExport    = '*'
	AliasesToExport      = '*'

	PrivateData          = @{
		PSData = @{
			Tags       = @('PemCore', 'PSEdition_Core', 'Windows', 'Linux', 'macOS')
			ProjectUri = 'https://oneget.org'
		}
	}
}

