//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfwebapp.ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemQuery", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class SystemQuery : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string contextField;
        
        private string nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemQueryResponseWcf", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class SystemQueryResponseWcf : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfwebapp.ServiceReference2.ISYSTEMQueryNIEMwcf")]
    public interface ISYSTEMQueryNIEMwcf
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISYSTEMQueryNIEMwcf/RetrieveQuery", ReplyAction="http://tempuri.org/ISYSTEMQueryNIEMwcf/RetrieveQueryResponse")]
        wcfwebapp.ServiceReference2.SystemQueryResponseWcf RetrieveQuery(wcfwebapp.ServiceReference2.SystemQuery SystemQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISYSTEMQueryNIEMwcf/RetrieveQuery", ReplyAction="http://tempuri.org/ISYSTEMQueryNIEMwcf/RetrieveQueryResponse")]
        System.Threading.Tasks.Task<wcfwebapp.ServiceReference2.SystemQueryResponseWcf> RetrieveQueryAsync(wcfwebapp.ServiceReference2.SystemQuery SystemQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISYSTEMQueryNIEMwcf/GetData", ReplyAction="http://tempuri.org/ISYSTEMQueryNIEMwcf/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISYSTEMQueryNIEMwcf/GetData", ReplyAction="http://tempuri.org/ISYSTEMQueryNIEMwcf/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISYSTEMQueryNIEMwcfChannel : wcfwebapp.ServiceReference2.ISYSTEMQueryNIEMwcf, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SYSTEMQueryNIEMwcfClient : System.ServiceModel.ClientBase<wcfwebapp.ServiceReference2.ISYSTEMQueryNIEMwcf>, wcfwebapp.ServiceReference2.ISYSTEMQueryNIEMwcf
    {
        
        public SYSTEMQueryNIEMwcfClient()
        {
        }
        
        public SYSTEMQueryNIEMwcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SYSTEMQueryNIEMwcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SYSTEMQueryNIEMwcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SYSTEMQueryNIEMwcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public wcfwebapp.ServiceReference2.SystemQueryResponseWcf RetrieveQuery(wcfwebapp.ServiceReference2.SystemQuery SystemQuery)
        {
            return base.Channel.RetrieveQuery(SystemQuery);
        }
        
        public System.Threading.Tasks.Task<wcfwebapp.ServiceReference2.SystemQueryResponseWcf> RetrieveQueryAsync(wcfwebapp.ServiceReference2.SystemQuery SystemQuery)
        {
            return base.Channel.RetrieveQueryAsync(SystemQuery);
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
    }
}
